// <auto-generated />
namespace EnrollmentApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class StudentUpdate_Illustration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StudentUpdate_Illustration));
        
        string IMigrationMetadata.Id
        {
            get { return "201810102215396_StudentUpdate_Illustration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
